version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - BRANCH=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | awk -F '/' '{print $3}')
      - PULL_BRANCH=$BRANCH
      - echo Logging into Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker pull $REPOSITORY_URL:$BRANCH || (docker pull $REPOSITORY_URL:master && PULL_BRANCH=master) || true
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $REPOSITORY_URL:$BRANCH
  post_build:
    commands:
      - echo Build completed `date`
      - echo Pushing image
      - docker push $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPOSITORY_URL:$BRANCH
